# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Mon Jun  2 19:48:25 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

#Edited By: # -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Mon Jun  2 19:48:25 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

#Edited By: #Daryl W. Bennett --kd8bny@gmail.com 
#QWT5 support added using makeQWT V1 R1 

from PyQt4 import QtCore, QtGui
from PyQt4.Qwt5 import * 

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(640, 410)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 620, 391))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.welcomeTab = QtGui.QWidget()
        self.welcomeTab.setObjectName(_fromUtf8("welcomeTab"))
        self.welcome = QtGui.QGraphicsView(self.welcomeTab)
        self.welcome.setGeometry(QtCore.QRect(30, 40, 261, 251))
        self.welcome.setFrameShape(QtGui.QFrame.WinPanel)
        self.welcome.setFrameShadow(QtGui.QFrame.Sunken)
        self.welcome.setCacheMode(QtGui.QGraphicsView.CacheBackground)
        self.welcome.setOptimizationFlags(QtGui.QGraphicsView.DontAdjustForAntialiasing)
        self.welcome.setObjectName(_fromUtf8("welcome"))
        self.label = QtGui.QLabel(self.welcomeTab)
        self.label.setGeometry(QtCore.QRect(410, 280, 101, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.AnalogClock = QwtAnalogClock(self.welcomeTab)
        self.AnalogClock.setGeometry(QtCore.QRect(350, 50, 206, 206))
        self.AnalogClock.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.AnalogClock.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.AnalogClock.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.AnalogClock.setLineWidth(4)
        self.AnalogClock.setFrameShadow(QwtDial.Plain)
        self.AnalogClock.setMode(QwtDial.RotateNeedle)
        self.AnalogClock.setObjectName(_fromUtf8("AnalogClock"))
        self.tabWidget.addTab(self.welcomeTab, _fromUtf8(""))
        self.carTab = QtGui.QWidget()
        self.carTab.setObjectName(_fromUtf8("carTab"))
        self.F_lights = QtGui.QToolButton(self.carTab)
        self.F_lights.setGeometry(QtCore.QRect(10, 30, 111, 71))
        self.F_lights.setObjectName(_fromUtf8("F_lights"))
        self.A_lights = QtGui.QToolButton(self.carTab)
        self.A_lights.setGeometry(QtCore.QRect(10, 110, 111, 71))
        self.A_lights.setObjectName(_fromUtf8("A_lights"))
        self.tabWidget.addTab(self.carTab, _fromUtf8(""))
        self.obdTab = QtGui.QWidget()
        self.obdTab.setObjectName(_fromUtf8("obdTab"))
        self.layoutWidget = QtGui.QWidget(self.obdTab)
        self.layoutWidget.setGeometry(QtCore.QRect(7, 13, 181, 201))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lcdNumber_speed = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_speed.setFrameShape(QtGui.QFrame.Box)
        self.lcdNumber_speed.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_speed.setObjectName(_fromUtf8("lcdNumber_speed"))
        self.gridLayout.addWidget(self.lcdNumber_speed, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 2)
        self.lcdNumber_rpm = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_rpm.setFrameShape(QtGui.QFrame.Box)
        self.lcdNumber_rpm.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_rpm.setObjectName(_fromUtf8("lcdNumber_rpm"))
        self.gridLayout.addWidget(self.lcdNumber_rpm, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 2)
        self.lcdNumber_inTemp = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_inTemp.setFrameShape(QtGui.QFrame.Box)
        self.lcdNumber_inTemp.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_inTemp.setObjectName(_fromUtf8("lcdNumber_inTemp"))
        self.gridLayout.addWidget(self.lcdNumber_inTemp, 2, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 1, 1, 2)
        self.lcdNumber_coolTemp = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_coolTemp.setFrameShape(QtGui.QFrame.Box)
        self.lcdNumber_coolTemp.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_coolTemp.setObjectName(_fromUtf8("lcdNumber_coolTemp"))
        self.gridLayout.addWidget(self.lcdNumber_coolTemp, 3, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 3, 1, 1, 2)
        self.lcdNumber_load = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumber_load.setFrameShape(QtGui.QFrame.Box)
        self.lcdNumber_load.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_load.setObjectName(_fromUtf8("lcdNumber_load"))
        self.gridLayout.addWidget(self.lcdNumber_load, 4, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 4, 1, 1, 2)
        self.obdButton = QtGui.QPushButton(self.layoutWidget)
        self.obdButton.setCheckable(False)
        self.obdButton.setAutoRepeat(False)
        self.obdButton.setAutoDefault(False)
        self.obdButton.setDefault(False)
        self.obdButton.setFlat(False)
        self.obdButton.setObjectName(_fromUtf8("obdButton"))
        self.gridLayout.addWidget(self.obdButton, 5, 0, 1, 3)
        self.obdClear = QtGui.QPushButton(self.obdTab)
        self.obdClear.setGeometry(QtCore.QRect(480, 330, 131, 27))
        self.obdClear.setObjectName(_fromUtf8("obdClear"))
        self.qwtPlot = QwtPlot(self.obdTab)
        self.qwtPlot.setGeometry(QtCore.QRect(210, 30, 400, 200))
        self.qwtPlot.setObjectName(_fromUtf8("qwtPlot"))
        self.tabWidget.addTab(self.obdTab, _fromUtf8(""))
        self.GPStab = QtGui.QWidget()
        self.GPStab.setObjectName(_fromUtf8("GPStab"))
        self.label_12 = QtGui.QLabel(self.GPStab)
        self.label_12.setGeometry(QtCore.QRect(340, 70, 66, 17))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.GPStab)
        self.label_13.setGeometry(QtCore.QRect(340, 100, 71, 17))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.GPSbutton = QtGui.QPushButton(self.GPStab)
        self.GPSbutton.setGeometry(QtCore.QRect(330, 280, 98, 27))
        self.GPSbutton.setObjectName(_fromUtf8("GPSbutton"))
        self.logGPS = QtGui.QPushButton(self.GPStab)
        self.logGPS.setGeometry(QtCore.QRect(330, 320, 98, 27))
        self.logGPS.setObjectName(_fromUtf8("logGPS"))
        self.Compass = QwtCompass(self.GPStab)
        self.Compass.setGeometry(QtCore.QRect(30, 80, 200, 200))
        self.Compass.setLineWidth(4)
        self.Compass.setObjectName(_fromUtf8("Compass"))
        self.tabWidget.addTab(self.GPStab, _fromUtf8(""))
        self.settingTab = QtGui.QWidget()
        self.settingTab.setObjectName(_fromUtf8("settingTab"))
        self.layoutWidget1 = QtGui.QWidget(self.settingTab)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 191, 331))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.layoutWidget1)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.pushButton_bt = QtGui.QPushButton(self.groupBox)
        self.pushButton_bt.setGeometry(QtCore.QRect(0, 30, 111, 27))
        self.pushButton_bt.setObjectName(_fromUtf8("pushButton_bt"))
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.layoutWidget1)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(17, 79, 73, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.spinBox_ATSP = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_ATSP.setGeometry(QtCore.QRect(122, 79, 38, 26))
        self.spinBox_ATSP.setToolTip(_fromUtf8(""))
        self.spinBox_ATSP.setWrapping(True)
        self.spinBox_ATSP.setReadOnly(False)
        self.spinBox_ATSP.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToNearestValue)
        self.spinBox_ATSP.setMinimum(1)
        self.spinBox_ATSP.setMaximum(5)
        self.spinBox_ATSP.setProperty("value", 1)
        self.spinBox_ATSP.setObjectName(_fromUtf8("spinBox_ATSP"))
        self.widget = QtGui.QWidget(self.groupBox_2)
        self.widget.setGeometry(QtCore.QRect(17, 25, 175, 23))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.usbRadio = QtGui.QRadioButton(self.widget)
        self.usbRadio.setObjectName(_fromUtf8("usbRadio"))
        self.horizontalLayout.addWidget(self.usbRadio)
        self.btRadio = QtGui.QRadioButton(self.widget)
        self.btRadio.setChecked(False)
        self.btRadio.setObjectName(_fromUtf8("btRadio"))
        self.horizontalLayout.addWidget(self.btRadio)
        self.devRadio = QtGui.QRadioButton(self.widget)
        self.devRadio.setEnabled(True)
        self.devRadio.setChecked(True)
        self.devRadio.setObjectName(_fromUtf8("devRadio"))
        self.horizontalLayout.addWidget(self.devRadio)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.layoutWidget1)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout.addWidget(self.groupBox_3)
        self.tabWidget.addTab(self.settingTab, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "pi2go V1 R4", None))
        self.label.setText(_translate("MainWindow", "pi2go V1 R4A", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.welcomeTab), _translate("MainWindow", "Welcome", None))
        self.F_lights.setText(_translate("MainWindow", "Fog Lights", None))
        self.A_lights.setText(_translate("MainWindow", "Accent Lights", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.carTab), _translate("MainWindow", "Car", None))
        self.label_3.setText(_translate("MainWindow", "Mph", None))
        self.label_2.setText(_translate("MainWindow", "RPM", None))
        self.label_4.setText(_translate("MainWindow", "deg (Intake)", None))
        self.label_5.setText(_translate("MainWindow", "deg (Coolant)", None))
        self.label_6.setText(_translate("MainWindow", "Load", None))
        self.obdButton.setText(_translate("MainWindow", "Start", None))
        self.obdClear.setText(_translate("MainWindow", "Clear Error Codes", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.obdTab), _translate("MainWindow", "OBDII", None))
        self.label_12.setText(_translate("MainWindow", "Latitude", None))
        self.label_13.setText(_translate("MainWindow", "Longitude", None))
        self.GPSbutton.setText(_translate("MainWindow", "Start", None))
        self.logGPS.setText(_translate("MainWindow", "Start Log", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.GPStab), _translate("MainWindow", "GPS", None))
        self.groupBox.setTitle(_translate("MainWindow", "Bluetooth", None))
        self.pushButton_bt.setText(_translate("MainWindow", "Connect Device", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "ODBII", None))
        self.label_7.setText(_translate("MainWindow", "ATSP Mode", None))
        self.usbRadio.setText(_translate("MainWindow", "USB", None))
        self.btRadio.setText(_translate("MainWindow", "BT", None))
        self.devRadio.setText(_translate("MainWindow", "Dev", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "GPS", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settingTab), _translate("MainWindow", "Settings", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

